### ISSUE TITLE
go版本的豆瓣插件貌似用不了

### ISSUE THREAD

**Issue by samwei12** [ykdsg/my_go#1]
rt

![202301221243846](https://learner.oss-cn-hangzhou.aliyuncs.com/img/202301221243846.png)

会一直卡在query 这里

**Comment by ykdsg** [comment]
这个问题还在吗？额，我本地是ok的。
![image](https://user-images.githubusercontent.com/644119/221777888-a6c6188d-4d1d-41d3-8737-96bf396315c8.png)
方便的话留下联系方式，可以进一步看下问题。

**Comment by samwei12** [comment]
还存在，我的邮箱  dongxiaosen@icloud.com

**Comment by ykdsg** [comment]
我怀疑是不是因为我本地是m1 版本导致的，重新打包了amd64 架构的版本，可以试试。https://github.com/ykdsg/my_go/releases/download/douban-workflow-1.1/douban-amd64-go.alfredworkflow

**Comment by ykdsg** [comment]
如果不是m1版本的问题，可以确认下本地到 https://www.douban.com/ 的网速，老实说douban的响应是挺慢的，很可能超时了。
